title: AdminLTE v3.2 Documentation
version: v3.2
description: AdminLTE v3.2 Documentation

baseurl: /docs/3.2
url: https://adminlte.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# No navigation items since all navigation files have been deleted
navigation: []
